package com.zclei.hitrise

import com.zclei.hitrise.model.AppLanguage

object UiStrings {
    fun get(language: AppLanguage, key: String): String =
        translations(language)[key] ?: ENGLISH[key] ?: key

    private fun translations(language: AppLanguage): Map<String, String> =
        when (language) {
            AppLanguage.Chinese -> CHINESE
            AppLanguage.English -> ENGLISH
            AppLanguage.French -> FRENCH
            AppLanguage.Thai -> THAI
        }

    private val CHINESE =
        mapOf(
            "activate" to "继续",
            "activation_failed" to "用户资料准备失败，请稍后重试。",
            "activation_just_now" to "刚刚",
            "activation_ready_subtitle" to "本机用户资料已准备好。你可以直接开始训练，也可以在设置里调整语言和蓝牙连接。",
            "activation_ready_title" to "训练已就绪",
            "activation_required" to "正在准备本机用户资料",
            "activation_subtitle" to "本机用户资料会自动生成，并用于同步训练数据。",
            "activation_title" to "用户资料",
            "average_frequency" to "平均频率",
            "best_30_hits" to "30 秒最佳",
            "best_60_hits" to "60 秒最佳",
            "best_burst" to "最佳 3 秒爆发",
            "burst_start" to "爆发起点",
            "calories_burned" to "消耗卡路里",
            "fat_burned" to "燃脂量",
            "calibrating_keep_quiet" to "正在启动蓝牙拳击计数",
            "calibration_fail_retry" to "蓝牙拳击计数启动失败，请检查设备连接后重试。",
            "calibration_fail_unstable" to "蓝牙连接不稳定，请检查设备后重试。",
            "cancel" to "取消",
            "cd_avatar_swatch" to "头像颜色 %d",
            "cloud_refresh" to "刷新云端",
            "cloud_sync_idle" to "等待下一次云端同步。",
            "code_hint" to "同步码",
            "code_invalid" to "同步码暂不可用，请稍后重试。",
            "done_short" to "完成",
            "error_short" to "错误",
            "history_title" to "训练记录",
            "hits" to "次",
            "hits_per_second" to "次/秒",
            "keep_quiet" to "请连接蓝牙设备",
            "language" to "APP 语言",
            "language_chinese" to "简体中文",
            "language_english" to "English",
            "language_french" to "Français",
            "language_helper" to "界面和训练提示会按照这里的语言显示。",
            "language_thai" to "ไทย",
            "latest_report" to "最新报告",
            "leaderboard_empty" to "暂无榜单数据。",
            "leaderboard_me" to "我的排名",
            "leaderboard_no_rank" to "当前尚未上榜。",
            "leaderboard_refresh" to "刷新榜单",
            "leaderboard_title" to "榜单排名",
            "lock_short" to "准备",
            "mode" to "模式",
            "no_history" to "暂无训练记录。",
            "no_report" to "暂无训练报告。",
            "page_leaderboard" to "榜单排名",
            "page_profile" to "个人中心",
            "page_training_achievements" to "锻炼成果",
            "page_training_center" to "锻炼中心",
            "permission_required" to "请先连接蓝牙设备。",
            "prepare_short" to "准备",
            "profile_avatar" to "个人头像",
            "profile_country" to "地区代码",
            "profile_edit" to "编辑资料",
            "profile_language" to "语言",
            "profile_nickname" to "昵称",
            "profile_title" to "个人中心",
            "ready" to "准备开始训练。",
            "retry_calibration" to "重新连接",
            "retry_short" to "重试",
            "save" to "保存",
            "serial_hint" to "用户ID",
            "serial_invalid" to "用户ID暂不可用，请稍后重试。",
            "settings" to "设置",
            "start" to "开始",
            "stop" to "结束",
            "tier" to "段位",
            "title" to "HitRise",
            "total_hits" to "总击打次数",
            "total_sessions" to "总训练次数",
            "training_complete" to "训练完成。",
            "training_failed" to "训练失败。",
            "training_live" to "正在训练",
            "training_stopped" to "训练已结束。",
        )

    private val ENGLISH =
        mapOf(
            "activate" to "Continue",
            "activation_failed" to "Profile setup failed. Please try again.",
            "activation_just_now" to "Just now",
            "activation_ready_subtitle" to "This device profile is ready. You can start training or adjust Bluetooth and language settings.",
            "activation_ready_title" to "Ready to Train",
            "activation_required" to "Preparing this device profile",
            "activation_subtitle" to "A local user profile is generated automatically for training sync.",
            "activation_title" to "User Profile",
            "average_frequency" to "Average frequency",
            "best_30_hits" to "Best 30s",
            "best_60_hits" to "Best 60s",
            "best_burst" to "Best 3-second burst",
            "burst_start" to "Burst start",
            "calories_burned" to "Calories",
            "fat_burned" to "Fat burn",
            "calibrating_keep_quiet" to "Starting Bluetooth punch counting",
            "calibration_fail_retry" to "Bluetooth punch counting failed to start. Check the device and retry.",
            "calibration_fail_unstable" to "Bluetooth connection is unstable. Check the device and retry.",
            "cancel" to "Cancel",
            "cd_avatar_swatch" to "Avatar color %d",
            "cloud_refresh" to "Refresh Cloud",
            "cloud_sync_idle" to "Waiting for the next cloud sync.",
            "code_hint" to "Sync code",
            "code_invalid" to "Sync code is temporarily unavailable.",
            "done_short" to "DONE",
            "error_short" to "ERR",
            "history_title" to "Training History",
            "hits" to "hits",
            "hits_per_second" to "hits/s",
            "keep_quiet" to "Connect the Bluetooth device",
            "language" to "App Language",
            "language_chinese" to "Simplified Chinese",
            "language_english" to "English",
            "language_french" to "French",
            "language_helper" to "UI text and training prompts follow this language setting.",
            "language_thai" to "Thai",
            "latest_report" to "Latest Report",
            "leaderboard_empty" to "No leaderboard data yet.",
            "leaderboard_me" to "My rank",
            "leaderboard_no_rank" to "You are not ranked yet.",
            "leaderboard_refresh" to "Refresh Leaderboard",
            "leaderboard_title" to "Leaderboard",
            "lock_short" to "WAIT",
            "mode" to "Mode",
            "no_history" to "No training history yet.",
            "no_report" to "No training session yet.",
            "page_leaderboard" to "Leaderboard",
            "page_profile" to "Profile",
            "page_training_achievements" to "Achievements",
            "page_training_center" to "Training",
            "permission_required" to "Connect the Bluetooth device first.",
            "prepare_short" to "READY",
            "profile_avatar" to "Avatar",
            "profile_country" to "Region code",
            "profile_edit" to "Edit Profile",
            "profile_language" to "Language",
            "profile_nickname" to "Nickname",
            "profile_title" to "Profile",
            "ready" to "Ready to train.",
            "retry_calibration" to "Reconnect",
            "retry_short" to "RETRY",
            "save" to "Save",
            "serial_hint" to "User ID",
            "serial_invalid" to "User ID is temporarily unavailable.",
            "settings" to "Settings",
            "start" to "Start",
            "stop" to "End",
            "tier" to "Tier",
            "title" to "HitRise",
            "total_hits" to "Total hits",
            "total_sessions" to "Total sessions",
            "training_complete" to "Training complete.",
            "training_failed" to "Training failed.",
            "training_live" to "Training live",
            "training_stopped" to "Training ended.",
        )

    private val FRENCH =
        mapOf(
            "activate" to "Continuer",
            "activation_failed" to "Échec de la préparation du profil. Veuillez réessayer.",
            "activation_just_now" to "À l'instant",
            "activation_ready_subtitle" to "Le profil de cet appareil est prêt. Vous pouvez commencer l'entraînement ou ajuster le Bluetooth et la langue.",
            "activation_ready_title" to "Prêt à s'entraîner",
            "activation_required" to "Préparation du profil de l'appareil",
            "activation_subtitle" to "Un profil local est généré automatiquement pour synchroniser l'entraînement.",
            "activation_title" to "Profil utilisateur",
            "average_frequency" to "Fréquence moyenne",
            "best_30_hits" to "Meilleur 30 s",
            "best_60_hits" to "Meilleur 60 s",
            "best_burst" to "Meilleure série de 3 s",
            "burst_start" to "Début de la série",
            "calories_burned" to "Calories",
            "fat_burned" to "Graisse brûlée",
            "calibrating_keep_quiet" to "Démarrage du comptage Bluetooth",
            "calibration_fail_retry" to "Le comptage Bluetooth n'a pas démarré. Vérifiez l'appareil et réessayez.",
            "calibration_fail_unstable" to "La connexion Bluetooth est instable. Vérifiez l'appareil et réessayez.",
            "cancel" to "Annuler",
            "cd_avatar_swatch" to "Couleur d'avatar %d",
            "cloud_refresh" to "Actualiser le cloud",
            "cloud_sync_idle" to "En attente de la prochaine synchronisation.",
            "code_hint" to "Code de synchronisation",
            "code_invalid" to "Code de synchronisation temporairement indisponible.",
            "done_short" to "FIN",
            "error_short" to "ERR",
            "history_title" to "Historique",
            "hits" to "coups",
            "hits_per_second" to "coups/s",
            "keep_quiet" to "Connectez l'appareil Bluetooth",
            "language" to "Langue de l'app",
            "language_chinese" to "Chinois simplifié",
            "language_english" to "Anglais",
            "language_french" to "Français",
            "language_helper" to "Les textes et les invites d'entraînement suivent cette langue.",
            "language_thai" to "Thaï",
            "latest_report" to "Dernier rapport",
            "leaderboard_empty" to "Aucune donnée de classement.",
            "leaderboard_me" to "Mon rang",
            "leaderboard_no_rank" to "Vous n'êtes pas encore classé.",
            "leaderboard_refresh" to "Actualiser le classement",
            "leaderboard_title" to "Classement",
            "lock_short" to "ATT",
            "mode" to "Mode",
            "no_history" to "Aucun historique pour le moment.",
            "no_report" to "Aucune séance pour le moment.",
            "page_leaderboard" to "Classement",
            "page_profile" to "Profil",
            "page_training_achievements" to "Résultats",
            "page_training_center" to "Entraînement",
            "permission_required" to "Connectez d'abord l'appareil Bluetooth.",
            "prepare_short" to "PRÊT",
            "profile_avatar" to "Avatar",
            "profile_country" to "Code région",
            "profile_edit" to "Modifier le profil",
            "profile_language" to "Langue",
            "profile_nickname" to "Pseudo",
            "profile_title" to "Profil",
            "ready" to "Prêt à s'entraîner.",
            "retry_calibration" to "Reconnecter",
            "retry_short" to "RÉESSAYER",
            "save" to "Enregistrer",
            "serial_hint" to "ID utilisateur",
            "serial_invalid" to "ID utilisateur temporairement indisponible.",
            "settings" to "Réglages",
            "start" to "Démarrer",
            "stop" to "Terminer",
            "tier" to "Niveau",
            "title" to "HitRise",
            "total_hits" to "Frappes totales",
            "total_sessions" to "Séances totales",
            "training_complete" to "Entraînement terminé.",
            "training_failed" to "Échec de l'entraînement.",
            "training_live" to "Entraînement en cours",
            "training_stopped" to "Entraînement terminé.",
        )

    private val THAI =
        mapOf(
            "activate" to "ดำเนินการต่อ",
            "activation_failed" to "ตั้งค่าโปรไฟล์ไม่สำเร็จ กรุณาลองใหม่",
            "activation_just_now" to "เมื่อสักครู่",
            "activation_ready_subtitle" to "โปรไฟล์อุปกรณ์พร้อมแล้ว คุณสามารถเริ่มฝึกหรือปรับ Bluetooth และภาษาได้",
            "activation_ready_title" to "พร้อมฝึก",
            "activation_required" to "กำลังเตรียมโปรไฟล์อุปกรณ์",
            "activation_subtitle" to "ระบบจะสร้างโปรไฟล์ในเครื่องโดยอัตโนมัติเพื่อซิงค์ข้อมูลการฝึก",
            "activation_title" to "โปรไฟล์ผู้ใช้",
            "average_frequency" to "ความถี่เฉลี่ย",
            "best_30_hits" to "ดีที่สุด 30 วินาที",
            "best_60_hits" to "ดีที่สุด 60 วินาที",
            "best_burst" to "ช่วง 3 วินาทีที่ดีที่สุด",
            "burst_start" to "เริ่มช่วงเร็ว",
            "calories_burned" to "แคลอรี",
            "fat_burned" to "เผาผลาญไขมัน",
            "calibrating_keep_quiet" to "กำลังเริ่มนับหมัดผ่าน Bluetooth",
            "calibration_fail_retry" to "เริ่มนับผ่าน Bluetooth ไม่สำเร็จ กรุณาตรวจสอบอุปกรณ์แล้วลองใหม่",
            "calibration_fail_unstable" to "การเชื่อมต่อ Bluetooth ไม่เสถียร กรุณาตรวจสอบอุปกรณ์แล้วลองใหม่",
            "cancel" to "ยกเลิก",
            "cd_avatar_swatch" to "สีรูปโปรไฟล์ %d",
            "cloud_refresh" to "รีเฟรชคลาวด์",
            "cloud_sync_idle" to "รอการซิงค์ครั้งถัดไป",
            "code_hint" to "รหัสซิงค์",
            "code_invalid" to "รหัสซิงค์ยังไม่พร้อมใช้งาน",
            "done_short" to "เสร็จ",
            "error_short" to "ผิดพลาด",
            "history_title" to "ประวัติการฝึก",
            "hits" to "ครั้ง",
            "hits_per_second" to "ครั้ง/วินาที",
            "keep_quiet" to "เชื่อมต่ออุปกรณ์ Bluetooth",
            "language" to "ภาษาแอป",
            "language_chinese" to "จีนตัวย่อ",
            "language_english" to "อังกฤษ",
            "language_french" to "ฝรั่งเศส",
            "language_helper" to "ข้อความและคำแนะนำการฝึกจะแสดงตามภาษานี้",
            "language_thai" to "ไทย",
            "latest_report" to "รายงานล่าสุด",
            "leaderboard_empty" to "ยังไม่มีข้อมูลอันดับ",
            "leaderboard_me" to "อันดับของฉัน",
            "leaderboard_no_rank" to "คุณยังไม่มีอันดับ",
            "leaderboard_refresh" to "รีเฟรชอันดับ",
            "leaderboard_title" to "อันดับ",
            "lock_short" to "รอ",
            "mode" to "โหมด",
            "no_history" to "ยังไม่มีประวัติการฝึก",
            "no_report" to "ยังไม่มีการฝึก",
            "page_leaderboard" to "อันดับ",
            "page_profile" to "โปรไฟล์",
            "page_training_achievements" to "ผลการฝึก",
            "page_training_center" to "ศูนย์ฝึก",
            "permission_required" to "โปรดเชื่อมต่ออุปกรณ์ Bluetooth ก่อน",
            "prepare_short" to "พร้อม",
            "profile_avatar" to "รูปโปรไฟล์",
            "profile_country" to "รหัสภูมิภาค",
            "profile_edit" to "แก้ไขโปรไฟล์",
            "profile_language" to "ภาษา",
            "profile_nickname" to "ชื่อเล่น",
            "profile_title" to "โปรไฟล์",
            "ready" to "พร้อมเริ่มฝึก",
            "retry_calibration" to "เชื่อมต่อใหม่",
            "retry_short" to "ลองใหม่",
            "save" to "บันทึก",
            "serial_hint" to "ID ผู้ใช้",
            "serial_invalid" to "ID ผู้ใช้ยังไม่พร้อมใช้งาน",
            "settings" to "ตั้งค่า",
            "start" to "เริ่ม",
            "stop" to "สิ้นสุด",
            "tier" to "ระดับ",
            "title" to "HitRise",
            "total_hits" to "จำนวนหมัดทั้งหมด",
            "total_sessions" to "จำนวนการฝึกทั้งหมด",
            "training_complete" to "ฝึกเสร็จแล้ว",
            "training_failed" to "การฝึกล้มเหลว",
            "training_live" to "กำลังฝึก",
            "training_stopped" to "สิ้นสุดการฝึกแล้ว",
        )
}
